# N.B. This file is sourced from /gdbtest/build/gdb/testsuite/site.exp.
set srcdir [file normalize $srcdir]

# N.B. This code is copied from gdb/testsuite/lib/append_gdb_boards_dir.exp.
proc append_gdbtest_boards_dir { name1 name2 op } {
    global gbenson_gdbtestdir
    global boards_dir

    set gdbtest_boards_dir "${gbenson_gdbtestdir}/boards"

    # Keep our board dir last in the list.
    set idx [lsearch -exact $boards_dir "$gdbtest_boards_dir"]
    if { $idx >= 0 } {
	set boards_dir [lreplace $boards_dir $idx $idx]
    }
    lappend boards_dir "${gdbtest_boards_dir}"
}
trace variable "boards_dir" w append_gdbtest_boards_dir
