#!/bin/sh

set -ex

topdir=$HOME

cd $topdir
outdir=$(date --iso-8601=date)
mkdir $outdir build  # Or bomb, if either exists.
logfile=$(echo $outdir | sed s/-//g)-1

rpm -qa | sort > $topdir/$outdir/rpm-qa.sort

unset CC_FOR_TARGET
unset CX_FOR_TARGET
crowbar="$topdir/gdbtest/crowbar"
[ -x $crowbar ]
$crowbar && exit 1
export RUNTESTFLAGS="CC_FOR_TARGET=$crowbar CXX_FOR_TARGET=$crowbar"

cd build
(CFLAGS="-g" \
 CXXFLAGS="-g" \
   ../src/configure \
     --with-system-readline \
     --with-separate-debug-dir=/usr/lib/debug \
     --with-gdb-datadir=$topdir/build/gdb/data-directory \
     --disable-binutils \
     --disable-gas \
     --disable-gold \
     --disable-gprof \
     --disable-intl \
     --disable-ld \
     --disable-sim \
  && make $(rpmbuild --eval='%{?_smp_mflags}') \
) 2>&1 | tee $topdir/$outdir/build.log
cp -a . ../$outdir/with-clang

make -k check \
  RUNTESTFLAGS="CC_FOR_TARGET=gcc CXX_FOR_TARGET=g++" \
  2>&1 | tee $topdir/$outdir/gcc-make-check.log
for ext in sum log; do
  cp -a gdb/testsuite/gdb.$ext \
    $topdir/gdbtest/back2back/baremetal-gcc-$logfile.$ext
done

cd ..
mv build $outdir/with-gcc
mv $outdir/with-clang build
cd build

make -k check \
  RUNTESTFLAGS="CC_FOR_TARGET=clang CXX_FOR_TARGET=clang++" \
  2>&1 | tee $topdir/$outdir/clang-make-check.log
for ext in sum log; do
  cp -a gdb/testsuite/gdb.$ext \
    $topdir/gdbtest/back2back/baremetal-clang-$logfile.$ext
done

cp -a . ../$outdir/with-clang
chmod -R -w ../$outdir
